### ISSUE TITLE
Stable rust supported?

### ISSUE THREAD

**Issue by Folyd** [Hexilee/unhtml.rs#10]
Seems like `unhtml_derive` doesn't support stable rust? Here is the error log when I compile in Rust V1.41.0 
```log
   Compiling hyper-tls v0.4.0
   Compiling reqwest v0.10.0
   Compiling unhtml_derive v0.7.4
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/wichna/.cargo/registry/src/github.com-1ecc6299db9ec823/unhtml_derive-0.7.4/src/lib.rs:1:1
  |
1 | #![feature(proc_macro_diagnostic)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `unhtml_derive`.

```

**Comment by Hexilee** [comment]
It supports now. Please update `unhtml_derive` to v0.7.5.

**Comment by Hexilee** [comment]
I'm going to close this issue, you can reopen it if the problem still exists.
